### ISSUE TITLE
Can't run demand for masterplan scenario!

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#228]
```
Executing: DemandTool C:\reference-case\masterplan Zurich
Start Time: Thu Jun 02 14:58:35 2016
Running script DemandTool...
reading input files
done
calculating thermal properties

Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\toolbox.py", line 144, in execute
    cea.demand.demand_calculation(locator=locator, weather_path=weather_path, gv=gv)
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\demand.py", line 59, in demand_calculation
    building_properties = read_building_properties(locator, gv)
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\demand.py", line 220, in read_building_properties
    prop_HVAC_result, surface_properties, gv)
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\functions.py", line 93, in get_prop_RC_model
    all_prop['Af'] = all_prop['footprint']*all_prop['floors']*all_prop['Hs']#*(1-all_prop.PARKING)*(1-all_prop.COOLROOM)*(1-all_prop.SERVERROOM) # conditioned area - áreas not heated
  File "C:\Users\darthoma\Anaconda2\envs\esri103\Lib\site-packages\pandas\core\frame.py", line 1635, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\Lib\site-packages\pandas\core\frame.py", line 1642, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\Lib\site-packages\pandas\core\generic.py", line 984, in _get_item_cache
    res = self._box_item_values(item, values)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\Lib\site-packages\pandas\core\frame.py", line 1844, in _box_item_values
    return self._box_col_values(values, items)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\Lib\site-packages\pandas\core\frame.py", line 1849, in _box_col_values
    name=items, fastpath=True)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\Lib\site-packages\pandas\core\series.py", line 235, in from_array
    return cls(arr, index=index, name=name, copy=copy, fastpath=fastpath)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\Lib\site-packages\pandas\core\series.py", line 132, in __init__
    data = SingleBlockManager(data, index, fastpath=True)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\Lib\site-packages\pandas\core\internals.py", line 3430, in __init__
    block = make_block(block, axis, axis, ndim=1, fastpath=True)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\Lib\site-packages\pandas\core\internals.py", line 1909, in make_block
    placement=placement)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\Lib\site-packages\pandas\core\internals.py", line 65, in __init__
    '%d' % (len(items), len(values)))
ValueError: Wrong number of items passed 242, indices imply 0

Failed to execute (DemandTool).
Failed at Thu Jun 02 14:58:38 2016 (Elapsed Time: 3.07 seconds)
```

**Comment by JIMENOFONSECA** [comment]
@daren-thomas try getting the radiation file (it was changed on the 2nd)

**Comment by martin-mosteiro** [comment]
Fixed the issues with the shapefiles, the demand runs fine now. I'll update the shapefiles on the reference case repository.
