### ISSUE TITLE
Embodied Energy does not work (`building_architecture.shp` file removed from reference-case?)

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#236]
```
Running script EmbodiedEnergyTool...

Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\toolbox.py", line 199, in execute
    lca_embodied(yearcalc=yearcalc, locator=locator, gv=gv)
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\embodied.py", line 80, in lca_embodied
    architecture_df = gpdf.from_file(locator.get_building_architecture()).drop('geometry', axis=1)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\Lib\site-packages\geopandas\geodataframe.py", line 161, in from_file
    return geopandas.io.file.read_file(filename, **kwargs)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\Lib\site-packages\geopandas\io\file.py", line 13, in read_file
    with fiona.open(filename, **kwargs) as f:
  File "C:\Users\darthoma\Anaconda2\envs\esri103\Lib\site-packages\fiona\__init__.py", line 168, in open
    raise IOError("no such file or directory: %r" % path)
IOError: no such file or directory: u'C:\\reference-case\\baseline\\inputs\\building-properties\\architecture.shp'

Failed to execute (EmbodiedEnergyTool).
Failed at Mon Jun 06 17:09:46 2016 (Elapsed Time: 0.00 seconds)
```

**Comment by daren-thomas** [comment]
I'm an idiot. Of course it works. We just need to run the `properties` script first.
