### ISSUE TITLE
Scenario Plots no longer work!

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#327]
C:\Users\darthoma\Anaconda2\envs\esri104\python.exe C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/plots/scenario_plots.py
Traceback (most recent call last):
  File "C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/plots/scenario_plots.py", line 169, in <module>
    test_plot_scenarios()
  File "C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/plots/scenario_plots.py", line 165, in test_plot_scenarios
    plot_scenarios(scenarios, output_file)
  File "C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/plots/scenario_plots.py", line 59, in plot_scenarios
    plot_lca_embodied(axes[0], locators, scenario_names, column='pen_MJm2', title='Primary Energy', unit='MJ/m2')
  File "C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/plots/scenario_plots.py", line 113, in plot_lca_embodied
    df[scenario] = scenario_data[column] * 1000 / scenario_data['GFA_m2']
  File "C:\Users\darthoma\Anaconda2\envs\esri104\lib\site-packages\pandas\core\frame.py", line 1914, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\darthoma\Anaconda2\envs\esri104\lib\site-packages\pandas\core\frame.py", line 1921, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\darthoma\Anaconda2\envs\esri104\lib\site-packages\pandas\core\generic.py", line 1090, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\darthoma\Anaconda2\envs\esri104\lib\site-packages\pandas\core\internals.py", line 3102, in get
    loc = self.items.get_loc(item)
  File "C:\Users\darthoma\Anaconda2\envs\esri104\lib\site-packages\pandas\core\index.py", line 1692, in get_loc
    return self._engine.get_loc(_values_from_object(key))
  File "pandas\index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas\index.c:3979)
  File "pandas\index.pyx", line 157, in pandas.index.IndexEngine.get_loc (pandas\index.c:3843)
  File "pandas\hashtable.pyx", line 668, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12265)
  File "pandas\hashtable.pyx", line 676, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12216)
KeyError: 'pen_MJm2'

Process finished with exit code 1

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, wasn't there an issue lately that changed the name of the `pen_MJm2` column?

**Comment by martin-mosteiro** [comment]
yes, `pen_` columns are now called `nre_pen_` after solving issue #28

**Comment by daren-thomas** [comment]
I pushed the fix directly to master. @JIMENOFONSECA: the operations output still uses `pen_` - is that correct??

If so, please close this issue.

**Comment by JIMENOFONSECA** [comment]
I am not sure, i believe martin was working on the renaming..
________________________________

**Comment by martin-mosteiro** [comment]
The csv files from the embodied, operation and mobility calculation all use `nre_pen_`

**Comment by daren-thomas** [comment]
@martin-mosteiro, I beg to differ. Please check the master branch: `cea/analysis/operation.py` line 154:

```
result['pen_GJ'] = result['Qhsf_pen_GJ'] + result['Qwwf_pen_GJ'] + result['QCf_pen_GJ'] + result['Ef_pen_GJ']
```

**Comment by martin-mosteiro** [comment]
Woops. Fixed it now.
