### ISSUE TITLE
Error message when running demand script on HQ/baseline

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#339]
I suspect this has to do with not running the data helper first, but of course we should fix this!

```
Executing: DemandTool C:\reference-case\reference-case-hq\baseline Zurich
Start Time: Tue Sep 13 11:30:07 2016
Running script DemandTool...
Using python: C:\Python27\ArcGIS10.4\python.exe
Path to demand script: C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py
Adding path to PYTHONPATH: C:\Users\darthoma\Documents\GitHub\CEAforArcGIS
Running demand calculation for scenario C:\reference-case\reference-case-hq\baseline
Running demand calculation with weather file C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\databases\CH\Weather\Zurich.epw
reading input files

Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\GUI\toolbox.py", line 192, in execute
    gv.log(stderr)
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\GUI\toolbox.py", line 24, in add_message
    arcpy.AddMessage(msg % kwargs)
TypeError: not enough arguments for format string

Failed to execute (DemandTool).
Failed at Tue Sep 13 11:30:11 2016 (Elapsed Time: 4.33 seconds)
```

**Comment by daren-thomas** [comment]
fixed in PR #342
