### ISSUE TITLE
Running Optimization_main needs refactoring

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CEAforArcGIS#453]
Optimization_main.py is not running completely. We need to check what is the issue. Preliminary glance points it may be because of the title of 'slave_ main' file. The file in the CEA master folder corresponding to this error is named as 'Slave_main' instead. The error is as follows:

C:\Users\Bhargava\Anaconda2\envs\esri104\python.exe C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py
Traceback (most recent call last):
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 13, in <module>
    import cea.optimization.conversion_storage.master.master_main as master
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\conversion_storage\master\master_main.py", line 13, in <module>
    import cea.optimization.conversion_storage.master.evaluation as evaluation_function
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\conversion_storage\master\evaluation.py", line 9, in <module>
    import cea.optimization.conversion_storage.slave.slave_main as sM
ImportError: No module named slave_main

Process finished with exit code 1

**Comment by BhargavaKrishnaSreepathi** [comment]
After refactoring 'Slave_main' to 'slave_main' and correcting a bracket in 'least_cost', a new error popped up

Traceback (most recent call last):
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 85, in <module>
    run_as_script(r'C:\reference-case-zug\baseline')
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 80, in run_as_script
    moo_optimization(locator=locator, weather_file= weather_file, gv=gv)
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 60, in moo_optimization
    network_features, gv)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\conversion_storage\master\master_main.py", line 98, in evolutionary_algo_main
    fitnesses = map(toolbox.evaluate, pop)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\conversion_storage\master\master_main.py", line 70, in objective_function
    network_features, gv)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\conversion_storage\master\evaluation.py", line 102, in evaluation_main
    solar_features, gv)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\conversion_storage\slave\slave_main.py", line 43, in slave_main
    storage_main.storage_optimization(locator, master_to_slave_vars, gv)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\conversion_storage\slave\seasonal_storage\storage_main.py", line 215, in storage_optimization
    os.path.join(locator.get_optimization_slave_results_folder, MS_Var.configKey + "_StorageFlag.csv"),
  File "C:\Users\Bhargava\Anaconda2\envs\esri104\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Users\Bhargava\Anaconda2\envs\esri104\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'instancemethod' has no len()

**Comment by daren-thomas** [comment]
Sorry about being pedantic, but we can only really refactor code that runs. This is just a bug. Or rather a series of bugs.

@JIMENOFONSECA: Can you help @BhargavaKrishnaSreepathi get the optimization code?
