### ISSUE TITLE
Error while running optimization_main.py

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CEAforArcGIS#467]
While running the optimization_main.py for the reference-case-zug and fixing two minor typos, I reached an error which occurs after the algorithm runs for few generations. I am attaching the error faced.

Traceback (most recent call last):
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 85, in <module>
    run_as_script(r'C:\reference-case-zug\baseline')
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 80, in run_as_script
    moo_optimization(locator=locator, weather_file= weather_file, gv=gv)
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 60, in moo_optimization
    network_features, gv)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\conversion_storage\master\master_main.py", line 174, in evolutionary_algo_main
    fitnesses = map(toolbox.evaluate, invalid_ind)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\conversion_storage\master\master_main.py", line 70, in objective_function
    network_features, gv)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\conversion_storage\master\evaluation.py", line 102, in evaluation_main
    solar_features, gv)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\conversion_storage\slave\slave_main.py", line 43, in slave_main
    storage_main.storage_optimization(locator, master_to_slave_vars, gv)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\conversion_storage\slave\seasonal_storage\storage_main.py", line 217, in storage_optimization
    print os.path.join(locator.get_optimization_slave_results_folder, MS_Var.configKey + "_StorageFlag.csv")
  File "C:\Users\Bhargava\Anaconda2\envs\esri104\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Users\Bhargava\Anaconda2\envs\esri104\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'instancemethod' has no len()

Process finished with exit code 1

The MS_Var.configkey when the run stops is 30.0810.7520.010010.14001110.2710.72000.17000010111011010110100111

The result is
                  0
0         0.765199
1   9799236.655953
2  41734160.986314

From my obervations, i think the error lies in os.path.join(locator.get_optimization_slave_results_folder, MS_Var.configKey + "_StorageFlag.csv") and of the three entities involved, locator.get_optimization_slave_results_folder is posing the issues

**Comment by BhargavaKrishnaSreepathi** [comment]
Ran the file again to test if the results are the same, the error is the same but the values are as following
locator.get_optimization_slave_results_folder 
<bound method InputLocator.get_optimization_slave_results_folder of <cea.inputlocator.InputLocator object at 0x14BF1AB0>>

MS_Var.configkey
40.560010.3610.0600001010.1910.80000.32111000000110110110101110

Result
              0
0  7.979038e-02
1  2.856396e+08
2  3.104071e+08

**Comment by daren-thomas** [comment]
try this: `os.path.join(locator.get_optimization_slave_results_folder(), MS_Var.configKey + "_StorageFlag.csv")`

The error message points to the solution: `object of type 'instancemethod' has no len()`. `get_optimization_slave_results_folder` was being passed in as a function instead of the results of calling the function, which is a string.

**Comment by BhargavaKrishnaSreepathi** [comment]
`os.path.join(locator.get_optimization_slave_results_folder(), MS_Var.configKey + "_StorageFlag.csv") ` worked and I was able to successfully run the optimization_main file.

I observed another bug (i suppose), where once in a while, like after running the optimization_main certain number of times, it starts showing an error, which was not making any sense. 

C:\Users\Bhargava\Anaconda2\envs\esri104\python.exe C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py
PRE-PROCESSING + SINGLE BUILDING OPTIMIZATION
Solar features extraction
Run substation model for each building separately
Run decentralized model for buildings
Create distribution file with all buildings connected
Traceback (most recent call last):
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 85, in <module>
    run_as_script(r'C:\reference-case-zug\baseline')
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 80, in run_as_script
    moo_optimization(locator=locator, weather_file= weather_file, gv=gv)
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 51, in moo_optimization
    weather_file, gv)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\preprocessing\preprocessing_main.py", line 73, in preproccessing
    summarize_network.network_main(locator, total_demand, building_names, gv, "all") #"_all" key for all buildings
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\conversion_storage\master\summarize_network.py", line 78, in network_main
    Electr_netw_total += substations[iteration].Electr_array_all_flat.values
ValueError: operands could not be broadcast together with shapes (8760,) (4975,) (8760,) 

Process finished with exit code 1

since it was working fine in the previous run, i replaced the reference-case-zug folder present in 'C:' with the one from GitHub, then did the demand calculation and ran the optimization_main.py, and this time it runs perfectly without any issue. I have saved the faulty folder for future reference, but it had many files which were different (found them using WinMerge Tool). So in future if we face such error, this might be a potential solution.

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi could you close the issue if it is ready?
