### ISSUE TITLE
Hot water tank calculation error

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#552]
I ran into an issue when running the sensitivity analysis procedure for the ninecubes test case:
```
Traceback (most recent call last):
  File "cea\analysis\sensitivity\sensitivity_demand_simulate.py", line 215, in <module>
    main()
  File "cea\analysis\sensitivity\sensitivity_demand_simulate.py", line 210, in main
    output_parameters=args.output_parameters)
  File "cea\analysis\sensitivity\sensitivity_demand_simulate.py", line 171, in simulate_demand_batch
    totals, time_series = simulate_demand_sample(locator, weather, output_parameters)
  File "cea\analysis\sensitivity\sensitivity_demand_simulate.py", line 113, in simulate_demand_sample
    totals, time_series = demand_main.demand_calculation(locator, weather_path, gv)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py", line 86, in demand_calculation
    weather_data)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py", line 100, in thermal_loads_all_buildings
    building, bpr, weather_data, usage_schedules, date, gv, locator)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\thermal_loads.py", line 201, in calc_thermal_loads
    bpr.occupancy)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\hotwater_loads.py", line 96, in calc_Qwwf
    Qww_st_ls, Tww_st, Qwwf = calc_Qww_st_ls(T_ext, Ta, Qww, Vww, Qww_dis_ls_r, Qww_dis_ls_nr, gv)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\hotwater_loads.py", line 195, in calc_Qww_st_ls
    Tww_st[k] = sto_m.solve_ode_storage(Tww_st_0, Qww_st_ls[k], Qd[k], Qwwf[k], Vww_0, gv)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\technologies\storagetank.py", line 111, in solve_ode_storage
    y = odeint(ode, Tww_st_0, t, args = (ql, qd, qc, gv.Pwater, gv.Cpw, Vtank))
  File "C:\Users\User\Anaconda2\envs\esri104\lib\site-packages\scipy\integrate\odepack.py", line 153, in odeint
    ixpr, mxstep, mxhnil, mxordn, mxords)
ZeroDivisionError: division by zero
```

Tracing back the error, it appears that the existing calculation process for hot water tank losses causes an error when the hot water demand for the building is zero for the whole year. In this case, the hot water tank size is set to 0 m3 (line 190 in hotwater_loads.py), which causes multiple problems, mainly:
- tank surface area Atank = f(1/V) = nan (line 56 of storagetank.py)
- Tww_st[k] cannot be solved (line 195) (causes the above `ZeroDivisionError`)

These issues can be solved by simply saying if the tank volume is 0, then the tank surface area is 0, the tank temperature is equal to nan and Qww_st_ls and Qwwf are 0.

@shanshanhsieh: as the original developer of this code, does the above proposal make sense to you? Could you check the changes I proposed on the corresponding branch?

**Comment by shanshanhsieh** [comment]
Good catch!
Just checked the modification you made, it make sense and we should implement it : )
