### ISSUE TITLE
Mechanical ventilation recirculation calculation error

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#558]
When running sensitivity analyses for the demand of the Hochschulquartier case study, I run into the following error:
```
Traceback (most recent call last):
  File "cea\analysis\sensitivity\sensitivity_demand_simulate.py", line 215, in <module>
    main()
  File "cea\analysis\sensitivity\sensitivity_demand_simulate.py", line 210, in main
    output_parameters=args.output_parameters)
  File "cea\analysis\sensitivity\sensitivity_demand_simulate.py", line 171, in simulate_demand_batch
    totals, time_series = simulate_demand_sample(locator, weather, output_parameters)
  File "cea\analysis\sensitivity\sensitivity_demand_simulate.py", line 113, in simulate_demand_sample
    totals, time_series = demand_main.demand_calculation(locator, weather_path, gv)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py", line 86, in demand_calculation
    weather_data)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py", line 100, in thermal_loads_all_buildings
    building, bpr, weather_data, usage_schedules, date, gv, locator)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\thermal_loads.py", line 140, in calc_thermal_loads
    rc_model_crank_nicholson_procedure.calc_rc_model_demand_heating_cooling(bpr, tsd, hoy, gv)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\rc_model_crank_nicholson_procedure.py", line 124, in calc_rc_model_demand_heating_cooling
    air_con_model_loads_flows_temperatures = airconditioning_model.calc_hvac_heating(tsd, t, gv)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\airconditioning_model.py", line 277, in calc_hvac_heating
    raise ValueError
ValueError
```

I traced it back to a case where **m_ve_mech = 0** (i.e., mechanical ventilation system is inactive, only recirculation air gets conditioned) and **qe_sen > 0** (i.e., sensible heating is needed). Under these circumstances, the supply air **ts = t3** is set to the default **cooling** temperature for HVAC.

@gabriel-happle is this just a typo? As a result, since the moisture gains are zero (i.e., **w5 = 0**) the enthalpy change **(h_ts_w5 - h_w5_t5) < 0** and thus **m_ve_recirculation < 0**... which causes the error above.

I'm changing line 226 to `t3 = gv.temp_sup_heat_hvac` - unless you have a rational which explains why the original line made sense.

**Comment by gabriel-happle** [comment]
Thank you @martin-mosteiro
