### ISSUE TITLE
Sampling for sensitivity analysis on Euler is broken

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#562]
The new database structure introduced in #549 is not compatible with the sampling code in Euler, generating the following error:

```
Creating samples morris 10
Traceback (most recent call last):
  File "/cluster/apps/python/2.7.6/x86_64/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/cluster/apps/python/2.7.6/x86_64/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/cluster/home/martinmo/CEAforArcGIS/cea/analysis/sensitivity/sensitivity_demand_samples.py", line 149, in <module>
    sampler_parameters=sampler_params)
  File "/cluster/home/martinmo/CEAforArcGIS/cea/analysis/sensitivity/sensitivity_demand_samples.py", line 73, in create_demand_samples
    pdf = pd.concat([pd.read_excel(locator.get_uncertainty_db(), group, axis=1) for group in variable_groups])
  File "/cluster/apps/python/2.7.6/x86_64/lib64/python2.7/site-packages/pandas-0.16.1-py2.7-linux-x86_64.egg/pandas/io/excel.py", line 151, in read_excel
    return ExcelFile(io, engine=engine).parse(sheetname=sheetname, **kwds)
  File "/cluster/apps/python/2.7.6/x86_64/lib64/python2.7/site-packages/pandas-0.16.1-py2.7-linux-x86_64.egg/pandas/io/excel.py", line 287, in parse
    **kwds)
  File "/cluster/apps/python/2.7.6/x86_64/lib64/python2.7/site-packages/pandas-0.16.1-py2.7-linux-x86_64.egg/pandas/io/excel.py", line 403, in _parse_excel
    sheet = self.book.sheet_by_name(asheetname)
  File "/cluster/home/martinmo/.local/lib64/python2.7/site-packages/xlrd/book.py", line 441, in sheet_by_name
    raise XLRDError('No sheet named <%r>' % sheet_name)
xlrd.biffh.XLRDError: No sheet named <'THERMAL'>
```

**Comment by martin-mosteiro** [comment]
I'm using the old uncertainty database on Euler for now, but the sensitivity analysis code for Euler should be adapted to the new database structure... @daren-thomas?
