### ISSUE TITLE
Heating coil script references an inexistent globalvar

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#568]
The heating coil script does the following (lines 50-55):
```
        try:
            result = sopt.newton(fh, trh0, maxiter=1000, tol=0.01).real - 273
        except RuntimeError:
            print (Qhsf, Qhsf_0, Ta_sup_hs, Ta_re_hs, Ths_sup_0, Ths_re_0, ma_sup_hs, ma_sup_0,Ta_sup_0, Ta_re_0)
            print gv.samples
            result = sopt.bisect(fh, 0, 350, xtol=0.01, maxiter=500).real - 273
```
....but `gv.samples` doesn't exist, which causes the following error:
```
Traceback (most recent call last):
  File "/cluster/apps/python/2.7.6/x86_64/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/cluster/apps/python/2.7.6/x86_64/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/cluster/home/martinmo/CEAforArcGIS/cea/analysis/sensitivity/sensitivity_demand_simulate.py", line 219, in <module>
    main()
  File "/cluster/home/martinmo/CEAforArcGIS/cea/analysis/sensitivity/sensitivity_demand_simulate.py", line 212, in main
    output_parameters=args.output_parameters)
  File "/cluster/home/martinmo/CEAforArcGIS/cea/analysis/sensitivity/sensitivity_demand_simulate.py", line 171, in simulate_demand_batch
    totals, time_series = simulate_demand_sample(locator, weather, output_parameters)
  File "/cluster/home/martinmo/CEAforArcGIS/cea/analysis/sensitivity/sensitivity_demand_simulate.py", line 113, in simulate_demand_sample
    totals, time_series = demand_main.demand_calculation(locator, weather_path, gv)
  File "/cluster/home/martinmo/CEAforArcGIS/cea/demand/demand_main.py", line 86, in demand_calculation
    weather_data)
  File "/cluster/home/martinmo/CEAforArcGIS/cea/demand/demand_main.py", line 100, in thermal_loads_all_buildings
    building, bpr, weather_data, usage_schedules, date, gv, locator)
  File "/cluster/home/martinmo/CEAforArcGIS/cea/demand/thermal_loads.py", line 182, in calc_thermal_loads
    gv)
  File "/cluster/home/martinmo/CEAforArcGIS/cea/demand/sensible_loads.py", line 169, in calc_temperatures_emission_systems
    Ta_sup_0, Ta_re_0, gv.Cpa, gv)
  File "/cluster/home/martinmo/.local/lib64/python2.7/site-packages/numpy/lib/function_base.py", line 2576, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/cluster/home/martinmo/.local/lib64/python2.7/site-packages/numpy/lib/function_base.py", line 2652, in _vectorize_call
    outputs = ufunc(*inputs)
  File "/cluster/home/martinmo/CEAforArcGIS/cea/technologies/heating_coils.py", line 54, in calc_heating_coil
    print gv.samples
AttributeError: 'GlobalVariables' object has no attribute 'samples'
```
So... problem.

**Comment by daren-thomas** [comment]
It looks like you can just delete that line, it's only a `print` statement after all...

**Comment by martin-mosteiro** [comment]
I know. And I did on my computer :) But I'll commit my latest updates as soon as the master branch is working again...
