### ISSUE TITLE
Installation of geopandas broken

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#651]
When following the current installation guide for setting up a the `cea` anaconda environment, geopandas (specifically GDAL) is not running.
This error happened after cleaning up the Windows PATH Environment variables and and setting up a brand new environment.

This is the error message after attempting to run the radiation script:
```
C:\Users\Gabriel\Anaconda2\envs\cea\python.exe C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_daysim/radiation_main.py
Traceback (most recent call last):
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_daysim/radiation_main.py", line 9, in <module>
    from cea.resources.radiation_daysim import create_gml
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\resources\radiation_daysim\create_gml.py", line 12, in <module>
    import gdal
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\osgeo\__init__.py", line 25, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\osgeo\__init__.py", line 21, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: The specified module could not be found.

Process finished with exit code 1
```

The following fix seemed to work:
- copy `C:\users\Gabriel\Anaconda2\envs\cea\proj.dll` to `C:\users\Gabriel\Anaconda2\envs\cea\Library\bin` and make sure the second folder is in your system environment (restart pycharm)

But warnings still persist:
```
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
```

**Comment by daren-thomas** [comment]
@gabriel-happle I wonder: uninstalling anaconda (the whole thing) and re-installing should, in my opinion, fix this for you.

Is this still an issue?

**Comment by gabriel-happle** [comment]
@daren-thomas I re-installed the whole thing.
Seems we are back to square 1 :(

```
C:\Users\Gabriel\Anaconda2\envs\cea\python.exe C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/tests/test_calc_thermal_loads.py
Traceback (most recent call last):
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/tests/test_calc_thermal_loads.py", line 7, in <module>
    from cea.demand.thermal_loads import calc_thermal_loads, BuildingProperties
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\demand\thermal_loads.py", line 11, in <module>
    from geopandas import GeoDataFrame as Gdf
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\geopandas\__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\geopandas\io\file.py", line 3, in <module>
    import fiona
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\fiona\__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\fiona\collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: DLL load failed: The specified module could not be found.

Process finished with exit code 1
```

**Comment by daren-thomas** [comment]
ugh! so. that works for you? weird, i can run this without any problems (except for the warnings but those don't change anything) 

@gabriel-happle  do you want to add a note to the installation guide for users experiencing this error?

**Comment by gabriel-happle** [comment]
OK. Assigning myself to this issue. Added this to the master directly. hope that's ok

**Comment by daren-thomas** [comment]
it's not. but nevermind. thanks!

**Comment by gabriel-happle** [comment]
OK. Sorry.
So branch and pull request next time.
