### ISSUE TITLE
Old radiation script not working

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#661]
I can't run the arcgis radiation on my machine!
I tried multiple scenarios from pycharm as well as from arcgis.

```
PyTables is not installed. No support for HDF output.
C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\databases\weather\Singapore.epw
complete calculating sunrise
Traceback (most recent call last):
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 508, in <module>
    longitude=args.longitude, year=args.year)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 493, in run_as_script
    weather_path=weather_path)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 97, in solar_radiation_vertical
    Burn(Simple_context, locator.get_terrain(), dem_rasterfinal, locator.get_temporary_folder(), dem_raster_extent, gv)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 455, in Burn
    RadiationDEM.save(DEMfinal)
RuntimeError: ERROR 010240: Could not save raster dataset to C:\Users\Gabriel\Documents\ArcGIS\Default.gdb\DEM_All2 with output format FGDBR.

Process finished with exit code 1
```

But I do have the specified Default.gdb:

![f9b4d6c4-3fe7-11e7-98b0-22debb8082ae](https://cloud.githubusercontent.com/assets/17002288/26439484/edccca6e-415a-11e7-92db-76dd260f968e.png)

**Comment by gabriel-happle** [comment]
```Executing: RadiationTool C:\cea-reference-case\reference-case-zug\baseline Zug 2014 46.9524055556 7.43958333333
Start Time: Thu May 25 14:57:28 2017
Running script RadiationTool...
longitude: 7.43958333333
latitude: 46.9524055556
['C:\\Users\\Gabriel\\Anaconda2\\envs\\cea\\python.exe', '-u', '-m', 'cea.cli', '--scenario', u'C:\\cea-reference-case\\reference-case-zug\\baseline', 'radiation', '--arcgis-db', 'C:\\Users\\Gabriel\\Documents\\ArcGIS\\Default.gdb', '--latitude', '46.9524055556', '--longitude', '7.43958333333', '--year', '2014', '--weather-path', 'c:\\users\\gabriel\\documents\\github\\ceaforarcgis\\cea\\databases\\weather\\Zug.epw']
PyTables is not installed. No support for HDF output.
c:\users\gabriel\documents\github\ceaforarcgis\cea\databases\weather\Zug.epw
complete calculating sunrise
Traceback (most recent call last):
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\cli.py", line 381, in <module>
    main()
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\cli.py", line 377, in main
    parsed_args.func(parsed_args)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\cli.py", line 177, in radiation
    weather_path=args.weather_path)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\resources\radiation_arcgis\radiation.py", line 97, in solar_radiation_vertical
    Burn(Simple_context, locator.get_terrain(), dem_rasterfinal, locator.get_temporary_folder(), dem_raster_extent, gv)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\resources\radiation_arcgis\radiation.py", line 455, in Burn
    RadiationDEM.save(DEMfinal)
RuntimeError: ERROR 010240: Could not save raster dataset to C:\Users\Gabriel\Documents\ArcGIS\Default.gdb\DEM_All2 with output format FGDBR.
```

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle what is the case study?

**Comment by gabriel-happle** [comment]
I think all of them. I tried ecocampus and zug.

**Comment by JIMENOFONSECA** [comment]
It works in my computer for all scenarios except ecocampus. @daren-thomas do you think this has to do with the installation of arcgis or something?

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle can you check you have the spatial analyst extension of arcgis enabled?

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA having a different error now.
Trying to run zug case study
```
C:\Users\Gabriel\Anaconda2\envs\cea\python.exe C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py
PyTables is not installed. No support for HDF output.
C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\databases\weather\Zug.epw
complete calculating sunrise
Traceback (most recent call last):
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 508, in <module>
    longitude=args.longitude, year=args.year)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 493, in run_as_script
    weather_path=weather_path)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 97, in solar_radiation_vertical
    Burn(Simple_context, locator.get_terrain(), dem_rasterfinal, locator.get_temporary_folder(), dem_raster_extent, gv)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 449, in Burn
    '0.5')  # creating raster of the footprints of the buildings
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\conversion.py", line 2290, in FeatureToRaster
    raise e
arcgisscripting.ExecuteError: ERROR 000871: Output raster: Unable to delete the output c:\Users\Gabriel\AppData\Local\Temp\AllRaster.
ERROR 000581: Invalid parameters.
Failed to execute (FeatureToRaster).


Process finished with exit code 1
```

**Comment by gabriel-happle** [comment]
after manually deleting the specified folder I ended up with the same error as before

C:\Users\Gabriel\Anaconda2\envs\cea\python.exe C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py
PyTables is not installed. No support for HDF output.
C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\databases\weather\Zug.epw
complete calculating sunrise
Traceback (most recent call last):
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 508, in <module>
    longitude=args.longitude, year=args.year)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 493, in run_as_script
    weather_path=weather_path)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 97, in solar_radiation_vertical
    Burn(Simple_context, locator.get_terrain(), dem_rasterfinal, locator.get_temporary_folder(), dem_raster_extent, gv)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 455, in Burn
    RadiationDEM.save(DEMfinal)
RuntimeError: ERROR 010240: Could not save raster dataset to C:\Users\Gabriel\Documents\ArcGIS\Default.gdb\DEM_All2 with output format FGDBR.

Process finished with exit code 1

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle mmm weird..

**Comment by JIMENOFONSECA** [comment]
mmm, @darenthomas are you facing this too?
________________________________

**Comment by gabriel-happle** [comment]
after deleting all (non-active) files in AppData/Temp and the Arcgis default.gdb I end up with this different error when running the old radiation script from pycharm:

```
C:\Users\Gabriel\Anaconda2\envs\cea\python.exe C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py
PyTables is not installed. No support for HDF output.
C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\databases\weather\Zug.epw
complete calculating sunrise
Traceback (most recent call last):
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 508, in <module>
    longitude=args.longitude, year=args.year)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 493, in run_as_script
    weather_path=weather_path)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 92, in solar_radiation_vertical
    simplification_tolerance=8, minimum_area=None)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\cartography.py", line 1266, in SimplifyBuilding
    raise e
arcgisscripting.ExecuteError: ERROR 000210: Cannot create output C:\Users\Gabriel\Documents\ArcGIS\Default.gdb\Simple_CQ
Failed to execute (SimplifyBuilding).


Process finished with exit code 1
```

Looks like arcgis has to create the default.gdb... Trying from ArcGIS now

**Comment by gabriel-happle** [comment]
for the reference:
(there are also some warnings in the log)

[radiation_succes_from_arcgis.txt](https://github.com/architecture-building-systems/CEAforArcGIS/files/1030746/radiation_succes_from_arcgis.txt)

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA now we are on the same page again.

getting this geometry error for EcoCampus:

```
Executing: RadiationTool C:\cea-reference-case\reference-case-ecocampus\baseline Singapore 2014 1.36666666667 103.833333333
Start Time: Fri May 26 11:29:44 2017
Running script RadiationTool...
longitude: 103.833333333
latitude: 1.36666666667
['C:\\Users\\Gabriel\\Anaconda2\\envs\\cea\\python.exe', '-u', '-m', 'cea.cli', '--scenario', u'C:\\cea-reference-case\\reference-case-ecocampus\\baseline', 'radiation', '--arcgis-db', 'C:\\Users\\Gabriel\\Documents\\ArcGIS\\Default.gdb', '--latitude', '1.36666666667', '--longitude', '103.833333333', '--year', '2014', '--weather-path', 'c:\\users\\gabriel\\documents\\github\\ceaforarcgis\\cea\\databases\\weather\\Singapore.epw']
PyTables is not installed. No support for HDF output.
c:\users\gabriel\documents\github\ceaforarcgis\cea\databases\weather\Singapore.epw
complete calculating sunrise
complete burning buildings into raster
complete calculating boundaries
c:\users\gabriel\documents\github\ceaforarcgis\cea\resources\radiation_arcgis\radiation.py:431: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  DataCentroids['FactorShade'] = 1
c:\users\gabriel\documents\github\ceaforarcgis\cea\resources\radiation_arcgis\radiation.py:432: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  DataCentroids['Freeheight'] = DataCentroids.height_ag
Traceback (most recent call last):
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\cli.py", line 381, in <module>
    main()
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\cli.py", line 377, in main
    parsed_args.func(parsed_args)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\cli.py", line 177, in radiation
    weather_path=args.weather_path)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\resources\radiation_arcgis\radiation.py", line 104, in solar_radiation_vertical
    CalcObservers(Simple_CQ, observers, DataFactorsBoundaries, path_arcgis_db, gv)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\resources\radiation_arcgis\radiation.py", line 314, in CalcObservers
    arcpy.Dissolve_management(Buffer_CQ0, Buffer_CQ1, "Name", "#", "SINGLE_PART", "DISSOLVE_LINES")
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\management.py", line 4329, in Dissolve
    raise e
arcgisscripting.ExecuteError: ERROR 999999: Error executing function.
Invalid Topology [Incomplete void poly.]
Failed to execute (Dissolve).


Completed script RadiationTool...
Succeeded at Fri May 26 11:30:36 2017 (Elapsed Time: 52.01 seconds)
```

**Comment by JIMENOFONSECA** [comment]
Yes that is what I get too. I believe it has to do with the scenario itself, can you check that all geometry is closed?

Try http://desktop.arcgis.com/en/arcmap/10.3/manage-data/editing-topology/finding-topology-errors-with-the-error-inspector.htm

This is ArcGIS issue so I guess checking on google about the error might help in here..

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA I tried repairing the geometry and changed some vertex of an overlapping building. No success. 
The internet says that the ERROR 999999 of ArcGIS is most of the time thrown because of 32bit Memory issues! They suggest splitting shapefiles.
E.g. here: http://support.esri.com/technical-article/000012368

I don't know what to do anymore.

By the way @daren-thomas and @JIMENOFONSECA I can also not run the radiation for Zurich and other case studies

![image](https://cloud.githubusercontent.com/assets/17002288/26484153/314cafd4-4223-11e7-8c50-b69711422b54.png)

**Comment by daren-thomas** [comment]
I too have troubles with the radiation script...

**Comment by martin-mosteiro** [comment]
I ran the old radiation script on the master branch on both the Zurich baseline and masterplan scenarios and it ran with no issues.

**Comment by martin-mosteiro** [comment]
I successfully ran the open reference case from ArcGIS (before I was running from Pycharm). I tried running Ecocampus from ArcGIS: **no success**.

**Comment by daren-thomas** [comment]
there seem to be multiple issues here. I'm working on a bug that states "ERROR 000732: Remove Features: Dataset C:\Users\darthoma\Documents\ArcGIS\Default.gdb\Non_overlap does not exist or is not supported" - I created a separate issue for that: #699

**Comment by daren-thomas** [comment]
I can run the Zug case study after following the steps explained in #699.

**Comment by daren-thomas** [comment]
I, too, get the `arcgisscripting.ExecuteError: ERROR 999999: Error executing function.` when running the ecocampus study.

**Comment by JIMENOFONSECA** [comment]
This issue is being handled in #685 @daren-thomas would you mind testing it there? I am facing another error for the ecocampus. The pandas dataframe runs out of memory while writing or reading. I checked online and it seems that it does not work good for Win32bit.should all we update to a win64 python?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA so... we close this issue?

The move to win64 is not one to take lightly. We can do this, but keep in mind that this might require about a week of work for me until we have everything up and running. Please link the sources you used to support the move.
