### ISSUE TITLE
Branch i643_Building Retrofit Potential Feature - Error when choosing more than one retrofitting criteria

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#681]
While testing branch i643, I found an issue:
- When using the cost criteria, an error occurs as seen in the following images:

(In this example I chose age and costs, however, even when I use the costs alone, the feature does not work.)

![error01_a](https://user-images.githubusercontent.com/16256867/27170180-459831f4-51ad-11e7-9a5e-583bb136ca15.jpg)

(Here's a snapshot of the error)

![error01_b](https://user-images.githubusercontent.com/16256867/27170230-7b6957e0-51ad-11e7-93a4-a1bf5cdf403d.jpg)

(and of course, the expected new scenario, i.e. "baseline_HVAC" is not created)

![error01_c](https://user-images.githubusercontent.com/16256867/27170283-a4982d44-51ad-11e7-8293-989108815ab2.jpg)

**Comment by amraladdin** [comment]
Here's a copy of the error text:

Executing: RetrofitPotentialTool C:\reference-case\baseline 2020 false retrofit_HVAC false 15 false 50 false 50 false 4 false 20 false 30 true 2 false 2 false 2 false 2 false 15 false 15 false 15
Start Time: Thu Jun 15 09:28:15 2017
Running script RetrofitPotentialTool...
['C:\\Users\\aelesawy\\Anaconda2\\envs\\cea\\python.exe', '-u', '-m', 'cea.cli', '--scenario', u'C:\\reference-case\\baseline', 'retrofit-potential', '--retrofit-target-date', '2020', '--name', 'retrofit_HVAC', '--heating-costs-threshold', '2']
Traceback (most recent call last):
  File "C:\Users\aelesawy\Anaconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\aelesawy\Anaconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\aelesawy\documents\github\ceaforarcgis\cea\cli.py", line 449, in <module>
    main()
  File "c:\users\aelesawy\documents\github\ceaforarcgis\cea\cli.py", line 445, in main
    parsed_args.func(parsed_args)
  File "c:\users\aelesawy\documents\github\ceaforarcgis\cea\cli.py", line 274, in retrofit_potential
    emissions_operation_criteria=args.emissions_operation_threshold)
  File "c:\users\aelesawy\documents\github\ceaforarcgis\cea\analysis\retrofit\retrofit_potential.py", line 96, in retrofit_main
    costs_totals = pd.read_csv(locator_baseline.get_costs_operation_file(criteria_name))
  File "C:\Users\aelesawy\Anaconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\aelesawy\Anaconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\aelesawy\Anaconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "C:\Users\aelesawy\Anaconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\aelesawy\Anaconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas\parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas\parser.c:4184)
  File "pandas\parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas\parser.c:8449)
IOError: File C:\reference-case\baseline\outputs\data\costs\Qhsf_cost_operation.csv does not exist

Completed script RetrofitPotentialTool...
Succeeded at Thu Jun 15 09:28:17 2017 (Elapsed Time: 1.29 seconds)

**Comment by JIMENOFONSECA** [comment]
@amraladdin my bad, you should run the feature operation costs first

![image](https://user-images.githubusercontent.com/8973186/27170505-bc791a3a-51e0-11e7-8342-89e220637333.png)

**Comment by JIMENOFONSECA** [comment]
I implemented this just now in slide 7 of the presentation

**Comment by amraladdin** [comment]
Moved to #643
